# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aea64916d3833a6ade13c624d379db8732c17ecb7dc924c6488f26edbbb82751979bfe8cb8747eb595849c95fbc85c2a459643c6ac69e9fe0bfde8df2caf3f62

test:
  secret_key_base: 37a7d0585aa5a1cc1f2aba6f21972fbde79c36ee601265b9c11a1f9790bdafade589c157a5aefbb5f62c674787d03255cfd8e625cfcd46e7ec05a8a62103ecc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
